# this file deploys the tutorials to shinyapps.io

on: [push, pull_request]

name: Deploy tutorials

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    container: bcmslab/rintro:latest
    steps:
      - name: Push to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='bcmslab', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "lapply(list.files('practice', full.names = TRUE, pattern = '*.Rmd', recursive = TRUE), function(x) rsconnect::deployDoc(x))"
          Rscript -e "lapply(list.files('homework', full.names = TRUE, pattern = '*.Rmd', recursive = TRUE), function(x) rsconnect::deployDoc(x))"
